### ISSUE TITLE
Python version 版本咨询

### ISSUE THREAD

**Issue by BaoyanWang** [theoqian/TransferLearning_NER#1]
请问楼主用的python 版本，
运行的时候出现
Traceback (most recent call last):
  File "main.py", line 222, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 208, in main
    "data/boson_test_result")
  File "main.py", line 112, in train
    train_data = preprocess_data(train_sentences, char2id, tag2id)
  File "/root/receiveData/TransferLearning_NER/data_utils.py", line 89, in preprocess_data
    tags = [tag2id[w[1]] for w in s]
KeyError: u'B-product_name'
错误，
谢谢

**Comment by theoqian** [comment]
python3.5
